[theme]
base = "light"
primaryColor = "#203B37"
backgroundColor = "#F8F5DC"
secondaryBackgroundColor = "#EEE8B2"
textColor = "#081B1B"
linkColor = "#5A8F76"
borderColor = "#96CDB0"
showWidgetBorder = true
showSidebarBorder = true
baseRadius = "10px"
buttonRadius = "8px"
font = "serif"
headingFont = "serif"
baseFontSize = 16
baseFontWeight = 400
headingFontWeights = [700, 700, 700, 600, 600, 600]
chartCategoricalColors = ["#203B37", "#5A8F76", "#C18D52", "#96CDB0", "#081B1B", "#EEE8B2"]
chartSequentialColors = ["#EEE8B2", "#DDE5AF", "#CAE0AD", "#B6DAAD", "#96CDB0", "#75AB8D", "#5A8F76", "#3C6558", "#203B37", "#081B1B"]
greenColor = "#5A8F76"
yellowColor = "#C18D52"
orangeColor = "#C18D52"
blueColor = "#203B37"
grayColor = "#5A8F76"
dataframeBorderColor = "#96CDB0"
dataframeHeaderBackgroundColor = "#EEE8B2"

[theme.sidebar]
backgroundColor = "#081B1B"
secondaryBackgroundColor = "#203B37"
textColor = "#EEE8B2"
primaryColor = "#96CDB0"
borderColor = "#5A8F76"
